steps:
  # Step 1: Build the Docker image from the Dockerfile
  # Tag it using the Git commit hash ($SHORT_SHA) for traceability
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/budget-exceeded-handler:$SHORT_SHA', '.']

  # Step 2: Push the image to Container Registry
  # This makes it available for deployment to Cloud Run
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/budget-exceeded-handler:$SHORT_SHA']

  # Step 3: Deploy the image to Cloud Run
  # The service is deployed with environment variables and public access enabled
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run', 'deploy', 'budget-exceeded-handler',
        '--image', 'gcr.io/$PROJECT_ID/budget-exceeded-handler:$SHORT_SHA',
        '--region', 'europe-west1',
        '--platform', 'managed',
        '--allow-unauthenticated',
        '--set-env-vars',
        'USE_GCP=true,PROJECT_ID=$PROJECT_ID,REGION=europe-west1,SERVICES=obsidian-calendar-task-sync',
        '--quiet'
      ]

# Set a timeout of 15 minutes for the entire build process
timeout: 900s

# Enable structured logging to Cloud Logging only
options:
  logging: CLOUD_LOGGING_ONLY