steps:
  # Paso 1: Construir la imagen Docker personalizada
  - name: 'gcr.io/cloud-builders/docker'
    args:
      ['build', '-t', 'gcr.io/$PROJECT_ID/budget-exceeded-handler', '.']

  # Paso 2: Subir la imagen a Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      ['push', 'gcr.io/$PROJECT_ID/budget-exceeded-handler']

  # Paso 3: Desplegar la imagen a Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run', 'deploy', 'budget-exceeded-handler',
        '--image', 'gcr.io/$PROJECT_ID/budget-exceeded-handler',
        '--region', 'europe-west1',
        '--platform', 'managed',
        '--allow-unauthenticated',
        '--quiet'
      ]

timeout: 900s
options:
  logging: CLOUD_LOGGING_ONLY
