steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'budget-exceeded-handler'
      - '--source=src'
      - '--region=europe-west1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--quiet'
      - '--entry-point=gunicorn -w 4 -b :8080 main:app'

timeout: 900s
options:
  logging: CLOUD_LOGGING_ONLY