steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: bash
    args:
      - -c
      - |
        # Desplegar el servicio en Cloud Run con un tiempo de espera extendido (600 segundos)
        gcloud run deploy budget-exceeded-handler \
          --source . \
          --region europe-west1 \
          --platform managed \
          --allow-unauthenticated \
          --timeout 600 \
          --project $PROJECT_ID

options:
  logging: CLOUD_LOGGING_ONLY
