steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'budget-exceeded-handler'     # Nombre del servicio
      - '--source=src'                # Subcarpeta con el código
      - '--region=europe-west1'       # Región
      - '--platform=managed'
      - '--allow-unauthenticated'     # Solo si debe estar abierto al público
      - '--quiet'                     # Omitir prompts interactivos

timeout: 900s
options:
  logging: CLOUD_LOGGING_ONLY
