steps:
  # Step 1: Build the custom Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      ['build', '-t', 'gcr.io/$PROJECT_ID/budget-exceeded-handler', '.']

  # Step 2: Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      ['push', 'gcr.io/$PROJECT_ID/budget-exceeded-handler']

  # Step 3: Deploy the image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run', 'deploy', 'budget-exceeded-handler',
        '--image', 'gcr.io/$PROJECT_ID/budget-exceeded-handler',
        '--region', 'europe-west1',
        '--platform', 'managed',
        '--allow-unauthenticated',
        '--quiet'
      ]

timeout: 900s
options:
  logging: CLOUD_LOGGING_ONLY